= contact mgmt app

The back-end is an Apache Isis app surfacing a REST API, with Swagger-generated stubs for Typescript

The front-end is an Ionic/Angular app using Typescript.


== ionic front-end

=== prereqs

per: http://ionicframework.com/getting-started/

* install Node.js v4: https://nodejs.org

* install ionic command line tools: https://www.npmjs.com/package/ionic +
+
[source,bash]
----
npm install -g ionic
----

* install/upgrade cordova +
+
[source,bash]
----
npm install -g cordova
----

* install gulp +
+
[source,bash]
----
npm install -g gulp
npm install -g typescript
----

sanity check: `tsc csv` should return v1.7.3 (or thereabouts)

optional: install Visual Studio Code (cross-platform) or similar


=== example app

Used as the basis for our front-end

per: http://blog.ionic.io/ionic-and-typescript-part-3/

copy of https://github.com/driftyco/ionic-typescript-example

To build:

[source,bash]
----
npm install
npm install tsd -g
tsd install
----

To run:

[source,bash]
----
ionic serve
----





== Next steps

* Change the login page to use a form

* Finders

** since the data is not large, might make sense to do client-side filtering using, eg https://github.com/djett41/ionic-filter-bar

* Make it pretty

** eg using http://ionicmaterial.com/



== Rosco's setup

[source,bash]
----
git clone
cd frontend
npm install gulp gulp-util bower gulp-contact gulp-sass gulk-minify-css gulp-rename shelljs gulp-tsc
ionic serve
----

backend... open up IntelliJ



== Dan's setup of ionic-filter-bar

=== Stepping stones

first, had a go at building the ionic-filter-bar itself:

[source,bash]
----
clone repo

npm install
bower install
gulp   # failed, per https://github.com/dlmanning/gulp-sass/issues/185
npm install gulp-sass
gulp
----

this just ran the component's own integration tests.  so I realized I needed to do the same in the `demo` folder:


[source,bash]
----
cd demo
npm install
bower install
gulp   # failed, again per https://github.com/dlmanning/gulp-sass/issues/185
npm install gulp-sass
gulp
----

Could then run:

[source,bash]
----
ionic serve
----

and all was happy.


=== Configuring contactapp to use...

following the setup instructions at https://github.com/djett41/ionic-filter-bar#setup:

[source,bash]
----
cd frontend
bower install ionic-filter-bar
----

installs the component over in `backend/webapp/src/main/webapp/frontend/lib`.

update `config.xml` with:

[source,xml]
----
<platform name="ios">
    <preference name="KeyboardDisplayRequiresUserAction" value="false"/>
</platform>
----

update `index.html` (adjusting for our location of js library files):

[source,html]
----
<link rel="stylesheet" href="lib/ionic-filter-bar/dist/ionic.filter.bar.css">
<script src="lib/ionic-filter-bar/dist/ionic.filter.bar.js"></script>
----

update `app.js`:

[source,javascript]
----
angular.module('starter', ['ionic', 'starter.controllers', 'ngResource', 'jett.ionic.filter.bar'])
----

update `ionic.app`:

[source]
----
@import "../backend/webapp/src/main/webapp/frontend/lib/ionic-filter-bar/scss/ionic.filter.bar";
----


== CORS testing

Moved `../backend/webapp/src/main/webapp/frontend` back to `www`.

Now run via `ionic serve`, which is localhost:8100 connecting to localhost:8080 (hardcoded)

To run, recommend:

[source,bash]
----
ionic serve --lab
----


== Ionic testing


per http://ionicframework.com/docs/guide/installation.html

* install Ant
* install Android SDK (24.4.1 at time of writing)
* using Android SDK Manager
  * install platform-tools (23.1)
  * install
* update `$ANDROID_HOME` to location
* update `$PATH` to include `$ANDROID_HOME/tools` and `$ANDROID_HOME/platform-tools`


per http://ionicframework.com/docs/cli/run.html

[source,bash]
----
ionic platform add ios
ionic platform add android
----


per http://ionicframework.com/docs/guide/testing.html

[source,bash]
----
ionic build android
----

to emulate, need to create an emulator image (avd).  According to the error message, use (adjust for platform):

[source,bash]
----
C:\Android-SDK\v24.4.1\tools\android.BAT avd
----

* download an intel image (I chose x86_64, since on a 64-bit windows)
* download the HAXM device driver

* enable VT-x in the bios...

then run the install:

* C:\Android-SDK\v24.4.1\extras\intel\Hardware_Accelerated_Execution_Manager\intelhaxm-android.exe




per http://docs.ionic.io/docs/cordova-whitelist


[source,bash]
----
ionic plugin add https://github.com/apache/cordova-plugin-whitelist.git
----

then edited `config.xml`


could then deploy

[source,bash]
----
ionic run android
----


nb: for debugging, use the link:https://developers.google.com/chrome-developer-tools/docs/remote-debugging[adb extension for Chrome]


note that the `./plugins` directory is ignored (via `.gitignore`); looks like can use `ionic state restore` to restore all plugins.





== Using swagger-ui

The `web.xml` is set up using "auto" for the security challenge.  The `swagger-ui/index.html` doesn't (not sure why) seem to be logging in correctly.  the workaround is to access the `/restful/swagger/public` URI directly from the web browser (causing an HTTP Basic auth challenge),

