= contact mgmt app

The back-end is an Apache Isis app surfacing a REST API, with Swagger-generated stubs for Typescript

The front-end is an Ionic/Angular app using Typescript.


== ionic front-end

=== prereqs

per: http://ionicframework.com/getting-started/

* install Node.js v4: https://nodejs.org

* install ionic command line tools: https://www.npmjs.com/package/ionic +
+
[source,bash]
----
npm install -g ionic
----

* install/upgrade cordova +
+
[source,bash]
----
npm install -g cordova
----

* install gulp +
+
[source,bash]
----
npm install -g gulp
npm install -g typescript
----

sanity check: `tsc csv` should return v1.7.3 (or thereabouts)

optional: install Visual Studio Code (cross-platform) or similar


=== example app

Used as the basis for our front-end

per: http://blog.ionic.io/ionic-and-typescript-part-3/

copy of https://github.com/driftyco/ionic-typescript-example

To build:

[source,bash]
----
npm install
npm install tsd -g
tsd install
----

To run:

[source,bash]
----
ionic serve
----





== Next steps

* Change the login page to use a form

* Finders

** since the data is not large, might make sense to do client-side filtering using, eg https://github.com/djett41/ionic-filter-bar

* Make it pretty

** eg using http://ionicmaterial.com/



== Rosco's setup

[source,bash]
----
git clone
cd frontend
npm install gulp gulp-util bower gulp-concat gulp-sass gulp-minify-css gulp-rename shelljs gulp-tsc
ionic serve
----

backend... open up IntelliJ



== Dan's setup of ionic-filter-bar

=== Stepping stones

first, had a go at building the ionic-filter-bar itself:

[source,bash]
----
clone repo

npm install
bower install
gulp   # failed, per https://github.com/dlmanning/gulp-sass/issues/185
npm install gulp-sass
gulp
----

this just ran the component's own integration tests.  so I realized I needed to do the same in the `demo` folder:


[source,bash]
----
cd demo
npm install
bower install
gulp   # failed, again per https://github.com/dlmanning/gulp-sass/issues/185
npm install gulp-sass
gulp
----

Could then run:

[source,bash]
----
ionic serve
----

and all was happy.


=== Configuring contactapp to use...

following the setup instructions at https://github.com/djett41/ionic-filter-bar#setup:

[source,bash]
----
cd frontend
bower install ionic-filter-bar
----

installs the component over in `backend/webapp/src/main/webapp/mobile/lib`.

update `config.xml` with:

[source,xml]
----
<platform name="ios">
    <preference name="KeyboardDisplayRequiresUserAction" value="false"/>
</platform>
----

update `index.html` (adjusting for our location of js library files):

[source,html]
----
<link rel="stylesheet" href="lib/ionic-filter-bar/dist/ionic.filter.bar.css">
<script src="lib/ionic-filter-bar/dist/ionic.filter.bar.js"></script>
----

update `app.js`:

[source,javascript]
----
angular.module('starter', ['ionic', 'starter.controllers', 'ngResource', 'jett.ionic.filter.bar'])
----

update `ionic.app`:

[source]
----
@import "../backend/webapp/src/main/webapp/mobile/lib/ionic-filter-bar/scss/ionic.filter.bar";
----


== CORS testing

Moved `../backend/webapp/src/main/webapp/mobile` back to `www`.

Now run via `ionic serve`, which is localhost:8100 connecting to localhost:8080 (hardcoded)

To run, recommend:

[source,bash]
----
ionic serve --lab
----


== Ionic testing

=== iOS

[source, bash]
----
git clone
cd frontend
npm install -g cordova ionic gulp
npm install gulp gulp-util bower gulp-concat gulp-sass gulp-minify-css gulp-rename shelljs gulp-tsc
----
You can test if everything went right by running:

[source, bash]
----
ionic serve --lab
----
If there are no errors, continue:

[source, bash]
----
sudo ionic platform add ios
sudo chown -R `whoami` platforms
----

Next, open up Xcode and open the Project:
contactapp-path/frontend/platforms/ios/ecp-contactapp.xcodeproj

Inside Xcode, select the correct build destination (Emulator or a connected debugging device) and run: 

* Product -> Clean (Cmd + Shift + K)
* Product -> Build (Cmd + B)
* Product -> Run (Cmd + R)

=== Android

per http://ionicframework.com/docs/guide/installation.html

* install Ant
* install Android SDK (24.4.1 at time of writing)
* using Android SDK Manager
  * install platform-tools (23.1)
  * install
* update `$ANDROID_HOME` to location
* update `$PATH` to include `$ANDROID_HOME/tools` and `$ANDROID_HOME/platform-tools`


per http://ionicframework.com/docs/cli/run.html

[source,bash]
----
ionic platform add ios
ionic platform add android
----


per http://ionicframework.com/docs/guide/testing.html

[source,bash]
----
ionic build android
----

to emulate, need to create an emulator image (avd).  According to the error message, use (adjust for platform):

[source,bash]
----
C:\Android-SDK\v24.4.1\tools\android.BAT avd
----

* download an intel image (I chose x86_64, since on a 64-bit windows)
* download the HAXM device driver

* enable VT-x in the bios...

then run the install:

* C:\Android-SDK\v24.4.1\extras\intel\Hardware_Accelerated_Execution_Manager\intelhaxm-android.exe




per http://docs.ionic.io/docs/cordova-whitelist


[source,bash]
----
ionic plugin add https://github.com/apache/cordova-plugin-whitelist.git
----

then edited `config.xml`


could then deploy

[source,bash]
----
ionic run android
----


nb: for debugging, use the link:https://developers.google.com/chrome-developer-tools/docs/remote-debugging[adb extension for Chrome]


note that the `./plugins` directory is ignored (via `.gitignore`); looks like can use `ionic state restore` to restore all plugins.





== Using swagger-ui

The `web.xml` is set up using "auto" for the security challenge.  The `swagger-ui/index.html` doesn't (not sure why) seem to be logging in correctly.  the workaround is to access the `/restful/swagger/public` URI directly from the web browser (causing an HTTP Basic auth challenge),




== Uploading

for use by ionic viewer

[source,bash]
----
ionic upload --note "first attempt, configured to talk to contacts.ecpnv.com over http"
----


generates an output such as:

[source,bash]
----
Email: dan@XXXXXX
Password: XXXXXXXXXXXXX
Logged in! :)
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...
Successfully uploaded (123d567f)

----

== License

[source]
----
Copyright 2015-2016 Eurocommercial Properties NV

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----

